spring:
  data:
    mongodb:
      auto-index-creation: false
      database: acal
      uri: mongodb+srv://acal-user:sDUrcOv9VcgLjLrG@cluster0.ddutk.gcp.mongodb.net/acal-user?retryWrites=true&w=majority
